# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard 'steering', :output_folder => "build/handlebars" do
 	watch(%r{^source/handlebars/.*\.handlebars$})
end